version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    # Point to the .env file inside the 'app' directory
    env_file:
      - ./app/.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
